apiVersion: v1
kind: ConfigMap
metadata:
  name: studentservice-config
data:
  DATABASE_SERVER: nagp-mysql.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: studentservice
  labels:
    app: studentservice
spec:
  ports:
    - port: 8080
  selector:
    app: studentservice
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentservice
  labels:
    app: studentservice
spec:
  replicas: 4
  selector:
    matchLabels:
      app: studentservice
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: studentservice
        tier: frontend
    spec:
      containers:
      - image: pkjjava/studentservice:0.0.2-SNAPSHOT
        name: studentservice
        env:
        - name: DATABASE_SERVER
          valueFrom:
            configMapKeyRef:
              name: studentservice-config
              key: DATABASE_SERVER          
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 8080
          name: studentservice
